var commandsIndex = {
    "book": [
        ["The Rust Programming Language", "https://doc.rust-lang.org/stable/book/"],
        ["Rust Async Book", "https://rust-lang.github.io/async-book/"],
        ["Rust Edition Guide Book", "https://doc.rust-lang.org/stable/edition-guide/"],
        ["The Cargo Book", "https://doc.rust-lang.org/cargo/index.html"],
        ["Rust and WebAssembly Book", "https://rustwasm.github.io/docs/book/"],
        ["The Embedded Rust Book", "https://rust-embedded.github.io/book/"],
        ["The Rust Cookbook", "https://rust-lang-nursery.github.io/rust-cookbook/"],
        ["Command line apps in Rust", "https://rust-cli.github.io/book/index.html"],
        ["Rust by Example", "https://doc.rust-lang.org/stable/rust-by-example/"],
        ["Rust RFC", "https://rust-lang.github.io/rfcs/"],
        ["The Rust Doc Book", "https://doc.rust-lang.org/rustdoc/index.html"],
        ["The rustc Book", "https://doc.rust-lang.org/rustc/index.html"],
        ["Guide to Rustc Development", "https://rustc-dev-guide.rust-lang.org/"],
        ["The Rust Reference", "https://doc.rust-lang.org/reference/index.html"],
        ["The Rustonomicon", "https://doc.rust-lang.org/nomicon/index.html"],
        ["The Unstable Book", "https://doc.rust-lang.org/unstable-book/index.html"],
        ["Rust bindgen User Guide", "https://rust-lang.github.io/rust-bindgen/"],
        ["The wasm-bindgen Guide", "https://rustwasm.github.io/docs/wasm-bindgen/"],
        ["Rust API Guidelines", "https://rust-lang.github.io/api-guidelines/"],
        ["Rust Fuzz Book", "https://rust-fuzz.github.io/book/"],
        ["Rust Forge Book", "https://forge.rust-lang.org/"],
    ],
    "yet": [
        ["Are we async yet?", "https://areweasyncyet.rs", "Asynchronous I/O in Rust"],
        ["Are we audio yet?", "https://areweaudioyet.com", "Audio related development in Rust"],
        ["Are we game yet?", "http://arewegameyet.com", "Rust game development"],
        ["Are we GUI yet?", "http://areweguiyet.com", "Rust GUI development"],
        ["Are we IDE yet?", "http://areweideyet.com", "Rust development environments"],
        ["Are we learning yet?", "http://www.arewelearningyet.com", "Rust machine learning ecosystem"],
        ["Are we web yet?", "http://arewewebyet.org", "Rust libraries for web development"],
        ["Are we podcast yet?", "https://soundcloud.com/arewepodcastyet", "Rust Are We Podcast Yet"],
        ["Are we IPFS yet?", "https://areweipfsyet.rs/", "Are We InterPlanetary File System (IPFS) Yet"],
    ],
    "tool": [
        ["Rust Playground", "https://play.rust-lang.org/"],
        ["cheats.rs", "https://cheats.rs/"],
        ["caniuse.rs", "https://caniuse.rs/"],
        ["Macro Railroad ", "https://lukaslueg.github.io/macro_railroad_wasm_demo/"],
    ],
    "mirror": [
        ["[CN] 清华大学开源软件镜像站-Rust Crates源", "https://mirrors.tuna.tsinghua.edu.cn/help/crates.io-index.git/"],
        ["[CN] 清华大学开源软件镜像站-Rustup源", "https://mirrors.tuna.tsinghua.edu.cn/help/rustup/"],
        ["[CN] 中国科学技术大学开源软件镜像站-Rust Crates源", "http://mirrors.ustc.edu.cn/help/crates.io-index.html"],
        ["[CN] 中国科学技术大学开源软件镜像站-Rust Toolchain源", "http://mirrors.ustc.edu.cn/help/rust-static.html"],
        ["[CN] 南京大学开源镜像站-Rust Crates源", "https://nju-mirror-help.njuer.org/rust-crates.html"],
        ["[CN] 上海交通大学开源镜像站-Rust Crates源", "https://mirrors.sjtug.sjtu.edu.cn/#/"],
        ["[CN] Rustcc.com源", "https://rustcc.com/article?id=6baecc6f-29ed-40d2-870b-343606aa2e93"],
    ]
};